### ISSUE TITLE
Unable to see lines and nodes in editor when building around a large star

### ISSUE THREAD

**Issue by morden96** [Touhma/DSP_Plugins#136]
Lines and Structure points are too small to see in editor. Recommend you scale the lines and points linearly with star size.
![image](https://user-images.githubusercontent.com/6688940/129597899-20bc9b17-28b6-4429-ab04-8e54ddbfa6d9.png)

**Comment by innominata** [comment]
you can zoom in with the mouse wheel

**Comment by morden96** [comment]
Zooming in moves you closer. A large sphere ends up behind your viewpoint
before you can see the node.

**Comment by innominata** [comment]
Hmm, ill have to look into that, in the meantime does making smaller spheres work?

**Comment by innominata** [comment]
Due to general bugginess with extremely large spheres, I've capped the dyson sphere max radius for new games as of 2.1b3
I tested on a 10x Blue giant and it worked fine. The previous version would crash when you tried to fill a segment.
New version will be available on our discord while we work on the planet grid rework before releasing it on here / thunderstore
