### ISSUE TITLE
Sorter "too close" warning and "needs foundation support" warning when running with CopyInserters mod.

### ISSUE THREAD

**Issue by Malacosa** [Touhma/DSP_Plugins#41]
When I play with Touhma_GalacticScale 1.1.2 and CopyInserters 1.0.6, I get the following

1) Place two belts running north-south near the equator of any planet directly adjacent to each other.  I can't place a sorter to take items from one belt to the other.  Get the sorter too close warning.  But when the belts are placed running east-west, no rpoblem.

2) Can't place ANY buildings.  Get the "needs foundation support"

If I downgrade to Touhma_GalacticScale 1.0.1, both these issues go away.

Would really love to have both mods working together, but for now, I'm downgrading to Touhma_GalacticScale 1.0.1, since you have specifically stated that anything higher is beta.

Love the mod, keep up the good work.

**Comment by GlitchHound** [comment]
I can't replicate #1 on seed 59243469
Of course #2 is the bigger blocker and I can replicate that. 
I can replicate both on Seed 36317648 - looks like #1 only affects larger planets, or perhaps it's related to the difference in sizes.
@Touhma worth noting #1 is present WITHOUT CopyInserters. 

#2 is fixed in the Transpilers branch :)

**Comment by GlitchHound** [comment]
The north-south problem is resolved in the aforementioned seed and we have good reason to believe that it should be resolved by latest work. I'm going to tie this to the next release but please do feel free to reopen if you stumble on it again after that.
