### ISSUE TITLE
when i used 1.3.0,my saved game with 1.1.2 could not open again

### ISSUE THREAD

**Issue by YondSun** [Touhma/DSP_Plugins#54]
I modified the planet generate algorithm config (like Class O,Blackhole……） and create a world，played 50+ hours.
But when I updated the mod(from 1.1.2 to 1.3.0)，my saved game could not open again.
I searched the web,saved game didn't save the universe,when I load the game, the universe will generate with the algorithm.If the generate algorithm config changed,the saved game couldnot open again.

I can give up that saved game,but my question is if the mod updated again(from1.3.0 to example 1.3.5 or 1.4.0 or…)，would my saved game abandon again？
I don't want to start over and over. Thank you.

**Comment by Touhma** [comment]
hey man ! 

Well as specified in the readme the game is still in beta state. so yeah save breaking changes are still coming that's why I don't recommand using it yet 

The 1.3 is kinda getting there in terms of stability but the 1.4 will break again ( I think ) 

Join us on the discord to know exactly what's happening with the mod :) 

But yeah between 1.1 & 1.3 I had to do some breaking changes
